on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '.github/workflows/*.yml'
      - '*.md'
  pull_request:
name: Flatpak
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:kde-5.15-23.08
      options: --privileged
    steps:
    - uses: actions/checkout@v4
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: gerbercam.flatpak
        manifest-path: org.flatpak.gerbercam.yaml
        cache-key: flatpak-builder-${{ github.sha }}

     - name: Create prerelease
      if: github.ref == 'refs/heads/master'
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: true
        automatic_release_tag: "ci_flat"
        title: "${{ steps.version.outputs.version }}"
        files: org.flatpak.gerbercam.flatpak
